### ISSUE TITLE
Failing to install version 0.1.1

### ISSUE THREAD

**Issue by Martin36** [forestagostinelli/deepxube#1]
When installing version 0.1.1 using pip, it does not include any source files. The `deepxube` folder only contains the `__init__py` file. 

Source files are added when running `pip install deepxube=0.1.0`

I am testing this on Ubuntu 20.04 in an Anaconda environment with python version 3.10.14

**Comment by forestagostinelli** [comment]
I think something went wrong with the publish.yml script. I'll work on fixing this.

In the meantime, you can get the 0.1.1 code from here: https://github.com/forestagostinelli/deepxube/releases/tag/0.1.1

**Comment by forestagostinelli** [comment]
This should now be fixed with `pip install deepxube==0.1.5`.
Please let me know if you have any other issues.
